s = set()

n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))
n = input("Enter Number: ")
s.add(int(n))

print("final set is: ", s)
print("length of set is: ", len(s))